# -*- coding: utf-8 -*-
"""Arquitetura monolíticae

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O46ZZhPgl9x4D74xkqWAvgZTx2D3_ua4
"""

#Inicialização do sistema
class EcommerceSystem:
    def __init__(self):
        # Listas vazias pra começar o banco de dados do zero
        self.users = []
        self.products = []
        self.orders = []

    # Serve pra jogar um nome novo na lista de usuários
    def add_user(self, user):
        self.users.append(user)

    # Aqui é pra cadastrar o que o site vai vender
    def add_product(self, product):
        self.products.append(product)

    # Lógica do pedido: só deixa comprar se o produto tiver na lista
    def place_order(self, user, product):
        if product in self.products:
            # Se tiver o produto, ele junta o nome do cliente com o item, e volta que o pedido foi feito
            self.orders.append((user, product))
            return "Pedido feito com sucesso"

        # Se o produto não tiver cadastrado, ele avisa que não tem o produto disponível
        return " "


# Criando o sistema pra rodar
system = EcommerceSystem()

# Colocando um usuário e um produto de teste
system.add_user("Alice")
system.add_product("Laptop")


# Rodando um loop pra simular 10 mil compras de uma vez e ver se aguenta
for i in range(10000):
    system.place_order("Alice", "Laptop")


# Mostra na tela se deu certo e o total de vendas que ficou salvo
print("Pedido feito com sucesso!!!")
print(len(system.orders))