# -*- coding: utf-8 -*-
"""arquitetura de microsserviços

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5GRURGEk1u05-rdl5STvLYoONoRqFG5
"""

#Essa parte só cuida de guardar os nomes dos usuários
class UserService:
    def __init__(self):
        self.users = []

    def add_user(self, user):
        self.users.append(user)


#Aqui serve para cadastrar e ver se o item está disponível
class ProductService:
    def __init__(self):
        self.products = []

    def add_product(self, product):
        self.products.append(product)

    #Essa parte checa se o produto existe na lista
    def check_availability(self, product):
        return product in self.products


#Aqui os pedidos são fechados
class OrderService:
    def __init__(self):
        self.orders = []

    #Para fechar a venda ele precisa perguntar pro 'ProductService' se tem o produto
    def place_order(self, user, product, product_service):
        if product_service.check_availability(product):
            self.orders.append((user, product))
            return "Pedido feito com sucesso"

        return "Produto não disponível"


#Colocando os motores pra funcionar
user_service = UserService()
product_service = ProductService()
order_service = OrderService()


#Colocando um usuario e um produto aleatorio para testar
user_service.add_user("Alice")
product_service.add_product("Laptop")


#Teste de carga
for i in range(10000):
    order_service.place_order(
        "Alice",
        "Laptop",
        product_service
    )


#Se o pedido foi feito com sucesso é printado aqui junto a quantidade de testes de carga
print("Pedido feito com sucesso!")
print(len(order_service.orders))